paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      responses:
        '200':
          description: 'Éxito: Lista de productos'
        '500':
          description: Error del servidor
